output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = "${module.eks.cluster_endpoint}"
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = "${module.eks.kubeconfig}"
}

output "base_domain" {
  value = "${var.base_domain}"
}

output "base_domain_zone_id" {
  value = "${var.base_domain_zone_id}"
}

output "cluster1_name" {
  value = "${lower(var.environment)}"
}

output "cluster1_ssl_certificate_arn" {
  value = "${module.eks.ssl_certificate_arn}"
}

output "worker_security_group_id" {
  description = "Security group ID attached to the EKS workers."
  value       = "${module.eks.worker_security_group_id}"
}

output "kubectl_usage" {
  value = "export KUBECONFIG=$KUBECONFIG:~/.kube/${lower(var.environment)}"
}

output "tags" {
  value = "${var.tags}"
}

output "worker_iam_role_arn" {
  description = "IAM role ID attached to EKS workers"
  value       = "${module.eks.worker_iam_role_arn}"
}
